# application-dev.yml (개발 환경)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:k6loadtest_dev}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 개발용 AWS 설정
aws:
  region: ${AWS_REGION:us-east-1}
  use-local-implementation: false

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.k6loadtest: DEBUG
